application:
  name: roi-calculator-DEV

server:
  port: 8011

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rpm_helthcare
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


